# @format

- hosts: phpmyadmin
  become: yes
  tasks:
    - name: bind_address_ip untuk luar ip
      include_role:
        name: phpmyadmin_mysql_nginx_php_backup
        tasks_from: bind_ip_out_mysql.yml
